c_compiler_version:    # [osx and x86_64]
  - 10                 # [osx and x86_64]
cxx_compiler_version:  # [osx and x86_64]
  - 10                 # [osx and x86_64]
MACOSX_SDK_VERSION:    # [osx and x86_64]
  - 10.12              # [osx and x86_64]
