{% set name = "squashfs-tools" %}
{% set version = "4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/squashfs/squashfs/squashfs{{ version }}/squashfs{{ version }}.tar.gz
  sha256: 0d605512437b1eb800b4736791559295ee5f60177e102e4d4ccd0ee241a5f3f6
  patches:
    - 0001-modern-compression.diff
    # Required for macOS support
    # In 4.4 https://github.com/plougher/squashfs-tools/pull/69 is used by homebrew but might only support 10.13+
    - pr3.patch

build:
  skip: True  # [not unix]
  number: 1003
  script:
    - cd squashfs-tools
    - make -j${CPU_COUNT} install

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - lz4-c
    - lzo
    - xz
    - zlib

test:
  commands:
    - mksquashfs ${RECIPE_DIR} recipe.fs
    - unsquashfs recipe.fs

about:
  home: https://sourceforge.net/projects/squashfs/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Tools for creating and unpacking squashfs filesystems'

  description: |
    Squashfs is a highly compressed read-only filesystem for Linux.
    It uses either gzip/xz/lzo/lz4 compression to compress both files, inodes
    and directories.  Inodes in the system are very small and all blocks are
    packed to minimise data overhead. Block sizes greater than 4K are supported
    up to a maximum of 1Mbytes (default block size 128K).

extra:
  recipe-maintainers:
    - sodre
    - mingwandroid
