{% set name = "squashfs-tools" %}
{% set version = "4.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plougher/squashfs-tools/archive/refs/tags/{{ version }}.tar.gz
  sha256: 94201754b36121a9f022a190c75f718441df15402df32c2b520ca331a107511c

build:
  skip: true  # [not unix]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - help2man
    - sed
  host:
    - lz4-c
    - lzo
    - xz
    - zlib
    - zstd

test:
  commands:
    - mksquashfs ${RECIPE_DIR} recipe.fs
    - unsquashfs recipe.fs

about:
  home: https://sourceforge.net/projects/squashfs/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Tools for creating and unpacking squashfs filesystems

  description: |
    Squashfs is a highly compressed read-only filesystem for Linux.
    It uses either gzip/xz/lzo/lz4 compression to compress both files, inodes
    and directories.  Inodes in the system are very small and all blocks are
    packed to minimise data overhead. Block sizes greater than 4K are supported
    up to a maximum of 1Mbytes (default block size 128K).

extra:
  recipe-maintainers:
    - sodre
    - mingwandroid
    - xhochy
