appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ajkdcYylzyNIUIQ3Z0P1rtkd8pnurz4SXtotrUqvJz+HGNYDdyHW2FyogH5+4zyOmCiuuWylZozzzwgMWkBEQU33OJHUHtEgnEGdB0nHwwe6OVXUOXmtXGV6EOBYu2FW1lBNFpfYcv4AhzmD+hZNzO8fJtfyPtkOjSGYESIumIBbjiG5J5CLCUDLgXdG6YQVtDXyGyW4pjfr15vyYFH7inSr8KmpjER1yxQxtsHZ8UGqtWoaJhH6WtEOFTuKI4+zCaNCSm9JtPKjBO1wg1Q2Sj6e+ui6ZkkRFIWKIW959bGIbe2+rARZdy0zs4dPOikxH8u0AmkeJZEHk3gW9ubxVZ8M1A7CL3KuxIxwpBIyABUpnhgku+6E5vwJKIvMY6RAkSaTbnO5UDInQa4VMoy+BLopBZeEf7J0dCYJ/tAqFyZ8vvgCYfFCBZQpwRtwlwOKvXpGhrLXkgQmmYjtZYcNSHgvrEwB2qtX/w+8MGgA4iTdnskSPYvQ5ExzSMDszdkfuGdCNXYGt8iw1n+zdTF0YsDRhWL742psCZIHebog5IifNRFkpoYuIpMlvPaaLaCinSdcBxscXJcsEXub6xvZ/CyNojM7VGS8SPNE8Ad7mB6+L6KtjBGcaPhyYLE3uwQG1yU4se9ElB7piCL7QoiUUXZpJ2jsTa5ilZHqJu68hcs=}
